config/routes.rb
Rails.application.routes.draw do
  root "boards#index"

  resources :boards, shallow: true do
    resources :board_columns, except: [ :index, :show ]
  end

  resources :cards,  except: [ :index ]

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/board.rb
class Board < ApplicationRecord
  has_many :board_columns, dependent: :destroy

  validates :name, presence: true
end

app/models/board_column.rb
class BoardColumn < ApplicationRecord
  include ActionView::RecordIdentifier

  belongs_to :board
  has_many :cards, dependent: :nullify

  validates :name, presence: true

  broadcasts_to ->(board_column) { "board_#{board_column.board_id}" }, inserts_by: :append, target: [ :board, :columns ]
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :board_column

  validates :title, presence: true

  acts_as_list scope: :board_column

  delegate :board, to: :board_column

  after_commit :touch_affected_board_columns

  private

  def touch_affected_board_columns
    if previous_changes[:board_column_id].present?
      board.board_columns.find(previous_changes[:board_column_id].first).touch
      board.board_columns.find(previous_changes[:board_column_id].last).touch
    else
      board_column.touch
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/board_columns_controller.rb
class BoardColumnsController < ApplicationController
  def new
    @board = Board.find(params[:board_id])
    @board_column = @board.board_columns.new
  end

  def edit
    @board_column = BoardColumn.find(params[:id])
  end

  def create
    @board = Board.find(params[:board_id])
    @board_column = @board.board_columns.new(board_column_params)

    respond_to do |format|
      if @board_column.save
        format.html { redirect_to board_url(@board), notice: "BoardColumn was successfully created." }
        format.turbo_stream
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    @board_column = BoardColumn.find params[:id]

    respond_to do |format|
      if @board_column.update(board_column_params)
        format.html { redirect_to board_url(@board_column.board), notice: "BoardColumn was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @board_column = BoardColumn.find params[:id]
    board = @board_column.board
    @board_column.destroy!

    respond_to do |format|
      format.html { redirect_to board_url(board), notice: "BoardColumn was successfully destroyed." }
      format.turbo_stream { render turbo_stream: turbo_stream.remove(@board_column) }
    end
  end

  private

  def board_column_params
    params.require(:board_column).permit(:name)
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: %i[ show edit update destroy ]

  def index
    @boards = Board.all.includes(:board_columns)
  end

  def show
    @board_columns = @board.board_columns.includes(:cards)
  end

  def new
    @board = Board.new
  end

  def edit
  end

  def create
    @board = Board.new(board_params)

    respond_to do |format|
      if @board.save
        format.html { redirect_to boards_url, notice: "Board was successfully created." }
        format.turbo_stream
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @board.update(board_params)
        format.html { redirect_to boards_url, notice: "Board was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @board.destroy!

    respond_to do |format|
      format.html { redirect_to boards_url, notice: "Board was successfully destroyed." }
      format.turbo_stream { render turbo_stream: turbo_stream.remove(@board) }
    end
  end

  private
    def set_board
      @board = Board.find(params[:id])
    end

    def board_params
      params.require(:board).permit(:name)
    end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def new
    @card = Card.new(board_column_id: params[:board_column_id])
  end

  def create
    service = Cards::CreateCardService.new(params: card_params)

    respond_to do |format|
      if service.call
        @card = service.card
        format.html { redirect_to board_url(@card.board), notice: "Card was successfully created." }
        format.turbo_stream
      else
        @card = service.card
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @card = Card.find(params[:id])
  end

  def update
    @card = Card.find(params[:id])
    service = Cards::UpdateCardService.new(card: @card, params: card_params)

    respond_to do |format|
      if service.call
        format.html { redirect_to board_url(@card.board_column.board), notice: "Card was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @card = Card.find(params[:id])
    board = @card.board_column.board
    Cards::DestroyCardService.new(card: @card).call

    respond_to do |format|
      format.html { redirect_to board_url(board), notice: "Card was successfully destroyed." }
      format.turbo_stream
    end
  end

  private
    def card_params
      params.require(:card).permit(:title, :description, :board_column_id, :position)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/board_columns/_board_column.html.erb
<div id= <%= dom_id(board_column)%> class="board-column" data-sortable-column-id-value="<%= board_column.id %>">
  <%= render partial: 'board_columns/column_header', locals: { board_column: board_column } %>

  <div id= <%= dom_id(board_column, :column_body) %> class="board-column-body", data-sortable-target="cardsContainer">
    <% board_column.cards.order(:position).each do |card| %>
      <%= render partial: 'cards/card', locals: { card: card } %>
    <% end %>
  </div>

  <div class="board-column-footer">
    <%= render partial: 'cards/new_card', locals: { board_column: board_column } %>
  </div>
</div>

app/views/board_columns/_column_header.html.erb
<%= turbo_frame_tag dom_id(board_column, :edit) do %>
  <div class="d-flex flex-row">
    <h5 class="d-flex flex-col">
      <%= board_column.name %>
    </h5>
    <div class="d-flex flex-col ms-auto gap-2">
        <%= link_to edit_board_column_path(board_column) do %>
          <div class="fa-solid fa-pencil text-primary-dark-600"></div>
        <% end %>
        <%= link_to board_column_path(board_column), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } do %>
          <div class="fa-solid fa-trash text-primary-dark-600"></div>
        <% end %>
    </div>
  </div>
<% end %>

app/views/board_columns/_form.html.erb
<%= form_with(model: [@board, @board_column], local: true, class: 'col-12') do |form| %>
  <% if @board_column.errors.any? %>
    <% @board_column.errors.full_messages.each do |message| %>
      <p class="text-center text-orange-600">
        <%= message %>
      </p>
    <% end %>
  <% end %>

  <div class="form-group">
    <%= form.text_field :name, placeholder: 'Column name', class: 'form-control' %>
  </div>

  <div class="actions mt-2 text-center">
    <%= link_to 'Cancel', board_path(@board_column.board), class: 'btn btn-outline-info' %>
    <%= form.submit 'Save', class: 'btn btn-outline-primary' %>
  </div>
<% end %>

app/views/board_columns/create.turbo_stream.erb
<%= turbo_stream.remove dom_id(BoardColumn.new) %>

<%= turbo_stream.append dom_id(@board, 'columns') do %>
  <%= render 'board_columns/board_column', board_column: @board_column %>
<% end %>

<%= turbo_stream.append dom_id(@board, 'columns') do %>
  <%= turbo_frame_tag dom_id(BoardColumn.new) %>
<% end %>

app/views/board_columns/edit.html.erb
<h1 class="text-primary-dark-500">Edit Board Column</h1>

<div class="row w-100 justify-content-center mt-3">
  <%= turbo_frame_tag dom_id(@board_column, :edit) do %>
    <div class="border border-primary-grey-200 bg-light p-2">
      <%= render 'form' %>
    </div>
  <% end %>
</div>

app/views/board_columns/new.html.erb
<h1 class="text-primary-dark-500">New Board Column</h1>

<div class="row w-100 justify-content-center mt-3">
  <%= turbo_frame_tag dom_id(@board_column) do %>
    <div class = 'board-column'>
      <div class="border border-primary-grey-200 bg-light p-2">
        <%= render 'form' %>
      </div>
    </div>
  <% end %>
</div>

app/views/boards/_board.html.erb
<div id= <%= dom_id(board) %> class="col-3 my-3">
  <div class="card border border-primary-grey-200">
    <%= turbo_frame_tag dom_id(board, :edit) do %>
      <div class="card-header bg-primary-grey-200">
        <div class="d-flex justify-content-between align-items-center">
          <h5 class="card-title mb-0">
            <%= link_to board.name, board, data: { turbo_frame: '_top'}, class: 'link-underline link-underline-opacity-0' %>
          </h5>
          <div class="d-flex gap-2">
            <%= link_to edit_board_path(board), class: 'text-default' do %>
              <i class="fa-solid fa-pencil text-primary-dark-600"></i>
            <% end %>
            <%= link_to board, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: 'text-danger' do %>
              <i class="fa-solid fa-trash text-primary-dark-600"></i>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
    <div class="card-body bg-primary-grey-100">
      <div class="card-text">
        <p>
        <%= "Columns: #{board.board_columns.size}" %>
        </p>
        <p>
        <%= "Cards: #{board.board_columns.joins(:cards).count}" %>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/boards/_form.html.erb
<%= form_for @board, class: 'col-12' do |form| %>
  <% if @board.errors.any? %>
    <% @board.errors.full_messages.each do |message| %>
      <p class="text-center text-orange-600">
      <%= message %>
      </p>
    <% end %>
  <% end %>

  <div class="row">
    <div class="col">
      <div class="form-group my-2">
        <%= form.text_field :name, placeholder: 'Board name', class: 'form-control' %>
      </div>
    </div>

    <div class="col d-flex align-items-end">
      <div class="actions mb-2 text-center">
        <%= link_to 'Cancel', boards_path, class: 'btn btn-outline-info' %>
        <%= form.submit 'Save', class: 'btn btn-outline-primary' %>
      </div>
    </div>
  </div>
<% end %>

app/views/boards/create.turbo_stream.erb
<%= turbo_stream.append 'boards' do %>
  <%= render 'boards/board', board: @board %>
<% end %>
<%= turbo_stream.replace dom_id(Board.new) do %>
  <%= link_to 'New Board', new_board_path, class: 'btn btn-outline-primary' %>
<% end %>

app/views/boards/edit.html.erb
<h1 class="text-primary-dark-500">Edit Board</h1>

<div class="row w-100 justify-content-center mt-3">
  <%= turbo_frame_tag dom_id(@board, :edit) do %>
    <div class="border border-primary-grey-200 bg-light p-2">
      <%= render 'form' %>
    </div>
  <% end %>
</div>

app/views/boards/index.html.erb
<div class="row w-100">
  <div class="d-flex justify-content-between">
    <%= link_to 'New Board', new_board_path, class: 'btn btn-outline-primary invisible' %>
    <h1 class="text-primary-dark-500">
      Boards
    </h1>
    <div>
      <%= turbo_frame_tag dom_id(Board.new) do %>
        <%= link_to 'New Board', new_board_path, class: 'btn btn-outline-primary' %>
      <% end %>
    </div>
  </div>
</div>

<div class="row w-100" id='boards'>
  <% @boards.each do |board| %>
    <%= render partial: 'boards/board', locals: { board: board } %>
  <% end %>
</div>

app/views/boards/new.html.erb
<h1 class="text-primary-dark-500">New Board</h1>

<div class="row w-100 justify-content-center mt-3">
  <%= turbo_frame_tag dom_id(@board) do %>
    <%= render 'form' %>
  <% end %>
</div>

app/views/boards/show.html.erb
<%= turbo_stream_from dom_id(@board) %>
<div class="board-header w-100 px-3">
  <div class="row">
    <div class="d-flex justify-content-between">
      <%= link_to 'Back to boards list', boards_path, class: 'text-primary-grey-600 ms-2' %>
      <h1 class="text-primary-dark-500">
        <%= @board.name %>
      </h1>
      <div>
        <%= link_to 'New Column', new_board_board_column_path(@board), data: { turbo_frame: dom_id(BoardColumn.new) }, class: 'btn btn-outline-primary' %>
      </div>
    </div>
  </div>
</div>

<div class="board-container">
  <div id= <%= dom_id(@board, 'columns') %> class="board-scroll p-3" data-controller="sortable" data-sortable-group-value="<%= @board.id %>" data-sortable-url-value="<%= card_path(":id") %>">
    <% @board_columns.each do |board_column| %>
      <%= render partial: 'board_columns/board_column', locals: { board_column: board_column } %>
    <% end %>
    <%= turbo_frame_tag dom_id(BoardColumn.new) %>
  </div>
</div>

app/views/cards/_card.html.erb
<%= turbo_frame_tag dom_id(card), data: { sortable_id: card.id} do %>
  <div class="card card-body my-1">
    <div class="d-flex justify-content-between align-items-center mb-2">
      <h5 class="card-title mb-0">
        <%= card.title %>
      </h5>
      <div class="d-flex gap-2">
        <%= link_to edit_card_path(card), class: 'text-default' do %>
          <i class="fa-solid fa-pencil"></i>
        <% end %>
        <%= link_to card_path(card), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: 'text-danger' do %>
          <i class="fa-solid fa-trash"></i>
        <% end %>
      </div>
    </div>
    <div class="card-text text-primary-grey-600">
      <%= card.description %>
    </div>
  </div>
<% end %>

app/views/cards/_form.html.erb
<%= form_with(model: @card, local: true, class: 'col-12') do |form| %>
  <% if @card.errors.any? %>
    <% @card.errors.full_messages.each do |message| %>
      <p class="text-center text-orange-600">
        <%= message %>
      </p>
    <% end %>
  <% end %>

  <%= form.hidden_field :board_column_id %>

  <div class="form-group my-2">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group my-2">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control', rows: 4 %>
  </div>

  <div class="row">
    <div class="actions mt-2 text-center">
      <%= link_to 'Cancel', board_path(@card.board), class: 'btn btn-outline-info' %>
      <%= form.submit 'Save', class: 'btn btn-outline-primary' %>
    </div>
  </div>
<% end %>

app/views/cards/_new_card.html.erb
<%= turbo_frame_tag dom_id(board_column, :new_card) do %>
  <%= link_to new_card_url(board_column_id: board_column.id), class: 'text-success fs-2' do %>
    <div class="fa-solid fa-plus"></div>
  <% end %>
<% end %>

app/views/cards/create.turbo_stream.erb
<%= turbo_stream.append dom_id(@card.board_column, :column_body) do %>
  <%= render 'cards/card', card: @card %>
<% end %>
<%= turbo_stream.replace dom_id(@card.board_column, :new_card) do %>
  <%= render 'cards/new_card', board_column: @card.board_column %>
<% end %>

app/views/cards/destroy.turbo_stream.erb
<%= turbo_stream.remove dom_id(@card) %>

app/views/cards/edit.html.erb
<h1 class="text-primary-dark-500">Edit Card</h1>

<div class="row w-100 justify-content-center mt-3">
  <%= turbo_frame_tag dom_id(@card) do %>
    <div class="border border-primary-grey-200 bg-light p-2">
      <%= render 'form' %>
    </div>
  <% end %>
</div>

app/views/cards/new.html.erb
<h1 class="text-primary-dark-500">New Card</h1>

<div class="row w-100 justify-content-center mt-3">
  <%= turbo_frame_tag dom_id(@card.board_column, :new_card) do %>
    <div class="border border-primary-grey-200 bg-light p-2">
      <%= render 'form' %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HotwireKanbanBoard</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="gradient-background">
      <div class="content-container bg-light">
        <%= yield %>
      </div>
    </div>
  </body>
</html>